# Include gitlab-ci-base.yml from cb-build-util.
#  Update the git hash to use a newer version of the base yaml
#  Note: This can be a branch name for testing but should be a git hash/tag for reproducability
include: 'https://gitlab.bit9.local/cbsensor/cb-build-util/raw/e962b8b2aa512e4d8b7fc8687201b9eea5128641/gitlab-ci-base.yml'

# Gitlab CI configuration script for event-collector-app.
variables:
  JENKINS_URL: https://jenkins-qa.cbenglab.com
  ARTIFACTORY_PATH: https://${ARTIFACTORY_URL}/artifactory
  ARTIFACTORY_REPO_PATH: carbonblack-pub/psc/tests/event-collector-app/linux/${CI_COMMIT_REF_NAME}
  BUILD_VERSION: ${CI_PIPELINE_ID} # Anything that starts with CI_ comes from gitlab}
  # Tells the  cb-build-util scripts that this isn't a conan package and it needs to be built like a project
  IS_PROJECT_REPO: 1


stages:
  - build
  - deploy
  - test

#---------------------------------------- Build -------------------------------------------#
build_triggered:
  extends: .build_triggered_template
  stage: build

build_branch:
  extends: .build_branch_template
  stage: build

build_release:
  extends: .build_release_template
  stage: build
#------------------------------------------------------------------------------------------#



#--------------------------------------- Deploy -------------------------------------------#
.deploy_script: &deploy_script |
  echo "No deploy stage right now"

.deploy:
  script: *deploy_script
  stage: deploy
  tags:
    - docker
    - docker-socket
  variables:
    GIT_STRATEGY: none

deploy_branch:
  extends: .deploy
  except:
    - master
    - /^release-/

deploy_release:
  extends: .deploy
  only:
    - master
    - /^release-/

#------------------------------------------------------------------------------------------#


#----------------------------------------- Test -------------------------------------------#
.test_script: &test_script |
  echo "No test script right now"

.test:
  script: *test_script
  stage: test
  tags:
    - docker
    - docker-socket
  variables:
    GIT_STRATEGY: none
  allow_failure: false


test_branch:
  extends: .test
  except:
    - master
    - /^release-/

test_release:
  extends: .test
  only:
    - master
    - /^release-/
#------------------------------------------------------------------------------------------#
